export const products = [
  {
    id: "1",
    title: "The Iconic Mesh Polo Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate4?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate17?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 95,
    colors: ["white", "black", "blue", "red"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "2",
    title: "Mesh Long-Sleeve Polo Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["navy", "gray", "white", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "3",
    title: "Soft Cotton Polo Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate4?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate5?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["red", "black", "green", "teal"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "4",
    title: "Custom Slim Fit Big Pony Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 115,
    colors: ["gray", "red", "black", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "5",
    title: "Original Fit Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 168,
    colors: ["navy", "green", "yellow", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "6",
    title: "Custom Slim Fit Stretch Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 98,
    colors: ["gray", "black", "blue", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "7",
    title: "Classic Fit Cotton-Linen Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["white", "red", "lightblue", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "8",
    title: "RLX CLARUS Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate4?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate5?$rl_df_pdp_5_7$",
    description: "RLX",
    content:
      "Ralph Lauren is proud to debut the RLX CLARUS® Polo Shirt—the first shirt of its kind made with CLARUS®, a textile innovation from Natural Fiber Welding, Inc. (NFW), that transforms our Polo shirt's natural cotton fibers into a breathable, high-performance fabric with moisture management and quick-drying attributes similar to plastic-based synthetic fabrics like polyester and nylon. Ralph Lauren is proud to partner with NFW as we continue our commitment to a more sustainable and equitable future.",
    price: 168,
    colors: ["white", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "9",
    title: "The Iconic Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["white", "black", "gray", "green"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "10",
    title: "Soft Cotton Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 115,
    colors: ["lightgreen", "orange", "lightgray", "ligtblue"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "11",
    title: "Performance Jersey Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["lightblue", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
  },
  {
    id: "12",
    title: "Mesh Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 125,
    colors: ["gray", "black", "navy"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    category: "New Arrivals",
  },
  {
    id: "13",
    title: "Soft Cotton Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 90,
    colors: ["navy", "brown", "lightblue", "burlywood"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    category: "New Arrivals",
  },
  {
    id: "14",
    title: "Polo Bear Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 125,
    colors: ["navy", "lightblue"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    category: "New Arrivals",
  },
  {
    id: "15",
    title: "Classic Fit Cotton-Linen Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["white", "red", "lightblue", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    category: "New Arrivals",
  },
  {
    id: "16",
    title: "Classic Fit Cotton-Linen Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["white", "red", "lightblue", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    category: "New Arrivals",
  },
  {
    id: "17",
    title: "Classic Fit Cotton-Linen Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["white", "red", "lightblue", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    category: "New Arrivals",
  },
];
