export const products = [
  {
    id: "1",
    title: "The Iconic Mesh Polo Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate4?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1350428_alternate17?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 95,
    colors: ["white", "black", "blue", "red"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "2",
    title: "Mesh Long-Sleeve Polo Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1429096_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["navy", "gray", "white", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "men",
  },
  {
    id: "3",
    title: "Soft Cotton Polo Shirt - All Fits",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate4?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266705_alternate5?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["red", "black", "green", "teal"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "4",
    title: "Custom Slim Fit Big Pony Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1294005_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 115,
    colors: ["gray", "red", "black", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "5",
    title: "Original Fit Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1442618_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 168,
    colors: ["navy", "green", "yellow", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "6",
    title: "Custom Slim Fit Stretch Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1400944_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 98,
    colors: ["gray", "black", "blue", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "7",
    title: "Classic Fit Cotton-Linen Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1435545_alternate4?$rl_df_pdp_5_7$",
    description: "Polo Ralph Lauren",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["white", "red", "lightblue", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "8",
    title: "RLX CLARUS Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate3?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate4?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1431482_alternate5?$rl_df_pdp_5_7$",
    description: "RLX",
    content:
      "Ralph Lauren is proud to debut the RLX CLARUS® Polo Shirt—the first shirt of its kind made with CLARUS®, a textile innovation from Natural Fiber Welding, Inc. (NFW), that transforms our Polo shirt's natural cotton fibers into a breathable, high-performance fabric with moisture management and quick-drying attributes similar to plastic-based synthetic fabrics like polyester and nylon. Ralph Lauren is proud to partner with NFW as we continue our commitment to a more sustainable and equitable future.",
    price: 168,
    colors: ["white", "black"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "9",
    title: "The Iconic Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1266710_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["white", "black", "gray", "green"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "10",
    title: "Soft Cotton Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455913_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 115,
    colors: ["lightgreen", "orange", "lightgray", "ligtblue"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "11",
    title: "Performance Jersey Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1397722_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 110,
    colors: ["lightblue", "white"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "12",
    title: "Mesh Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450900_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 125,
    colors: ["gray", "black", "navy"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "men",
  },
  {
    id: "13",
    title: "Soft Cotton Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1325702_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 90,
    colors: ["navy", "brown", "lightblue", "burlywood"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "men",
  },
  {
    id: "14",
    title: "Polo Bear Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450906_alternate4?$rl_df_pdp_5_7$",
    description: "Big & Tall",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 125,
    colors: ["navy", "lightblue"],
    size: ["XXL", "XL", "L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "15",
    title: "Custom Slim Fit Polo Bear Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 425,
    colors: ["black", "red"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "16",
    title: "Washed Piqué Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448895_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 395,
    colors: ["gray", "white"],
    size: ["L", "M"],
    sleeve: "Long Sleeve",
    category: "men",
  },
  {
    id: "17",
    title: "Custom Slim Fit Piqué Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448912_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 395,
    colors: ["gray", "white"],
    size: ["L", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "18",
    title: "Terry Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1399255_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 295,
    colors: ["blue", "black", "white"],
    size: ["L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "19",
    title: "Classic Fit Performance Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450840_alternate4?$rl_df_pdp_5_7$",
    description: "RLX Golf",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 115,
    colors: ["lightblue", "white"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "20",
    title: "Classic Fit Performance Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450801_alternate4?$rl_df_pdp_5_7$",
    description: "RLX Golf",
    content:
      "This striped Polo shirt features moisture-wicking properties to help keep you cool and comfortable on the course. Its lightweight, breathable stretch jersey is crafted with recycled polyester, reducing our dependence on virgin petroleum-based material.",
    price: 110,
    colors: ["pink", "black"],
    size: ["L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "21",
    title: "Classic Fit Performance Print Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1450808_alternate4?$rl_df_pdp_5_7$",
    description: "RLX Golf",
    content:
      "This striped Polo shirt features moisture-wicking properties to help keep you cool and comfortable on the course. Its lightweight, breathable stretch jersey is crafted with recycled polyester, reducing our dependence on virgin petroleum-based material.",
    price: 115,
    colors: ["black", "red"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "22",
    title: "Wool Piqué Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1372977_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 495,
    colors: ["black", "red"],
    size: ["XL", "M"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "23",
    title: "Custom Slim Fit Polo Bear Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate3?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1448627_alternate4?$rl_df_pdp_5_7$",
    description: "Purple Label",
    content:
      "An American style standard since 1972, the Polo shirt has been imitated but never matched. Over the decades, Ralph Lauren has reimagined his signature style in a wide array of colors and fits, yet all retain the quality and attention to detail of the iconic original. This relaxed version is made from our highly breathable cotton mesh, which offers a textured look and a soft feel.",
    price: 425,
    colors: ["black", "red"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "men",
  },
  {
    id: "24",
    title: "The Iconic Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate2?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate5?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "A Ralph Lauren icon, this Polo shirt is crafted from comfortable cotton mesh and finished with our signature embroidered Pony.",
    price: 45,
    colors: ["pink", "green", "blue", "yellow", "white", "gray", "black"],
    size: ["M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "25",
    title: "The Earth Polo",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1441708_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1441708_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "Designed with Mother Nature in mind, The Earth Polo is crafted from an innovative fabric made entirely from plastic bottles and dyed using a waterless process. To learn more about The Earth Polo and Ralph Lauren's sustainability initiatives, including our global commitment to using 170 million recycled plastic bottles in our products and packaging by 2025, please visit RalphLauren.com/earthpolo.",
    price: 45,
    colors: ["green", "red", "blue", "white"],
    size: ["M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "26",
    title: "Big Pony Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_alternate10?$rl_df_pdp_5_7_a10$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_lifestyle?$rl_df_pdp_5_7_lif$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_alternate2?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1264387_alternate4?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "This wear-with-anything Polo shirt is finished with our signature Big Pony and a '3' patch, representing the number worn by a polo team's strongest player.",
    price: 49,
    colors: ["white", "gray", "red", "yellow"],
    size: ["M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "27",
    title: "Performance Jersey Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1251136_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1251136_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "Made from moisture-wicking stretch jersey, this Polo shirt will keep him comfortable during class and practice.",
    price: 45,
    colors: ["navy", "red", "blue", "black", "white"],
    size: ["S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "28",
    title: "Performance Stretch Jersey Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1456632_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1456632_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "This Polo shirt's moisture-wicking fabric is crafted with recycled polyester, reinforcing Ralph Lauren's aim to create the highest-quality products with minimal harm to the environment.",
    price: 45,
    colors: ["green", "red"],
    size: ["L", "M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "29",
    title: "Cotton Mesh Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1456390_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1456390_alternate1?$rl_df_pdp_5_7$",
    src3: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate1?$rl_df_pdp_5_7$",
    src4: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate2?$rl_df_pdp_5_7$",
    src5: "https://www.rlmedia.io/is/image/PoloGSI/s7-1367132_alternate5?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "This classic Polo shirt is made from easy-to-care-for cotton mesh and finished with our signature embroidered Pony.",
    price: 50,
    colors: ["yellow", "orange", "green", "blue"],
    size: ["M", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "kids",
  },
  {
    id: "30",
    title: "Long-Sleeve Uniform Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1122879_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1122879_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "Combining breathable cotton mesh and our signature embroidered Pony, this classic Polo shirt is a back-to-school essential.",
    price: 45,
    colors: ["white", "black"],
    size: ["L", "S", "XS"],
    sleeve: "Long Sleeve",
    category: "kids",
  },
  {
    id: "31",
    title: "Cotton Mesh Uniform Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1122878_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1122878_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 2-7",
    content:
      "Essential for school uniforms, this classic polo shirt is crafted from soft cotton mesh and features our tonal signature embroidered pony at the left hem.",
    price: 39,
    colors: ["navy", "white"],
    size: ["M", "S", "XS"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "32",
    title: "US Open Ball Crew Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455643_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455643_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "Part of our 2022 US Open Tennis Championships collection, this Polo shirt is inspired by the tournament's official men's ball crew uniform, which was designed exclusively by Polo Ralph Lauren.",
    price: 85,
    colors: ["green", "white"],
    size: ["L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "33",
    title: "Big Pony Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455505_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455505_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "Finished with our iconic Big Pony, this Polo shirt features bold color-blocking in the season's vibrant shades.",
    price: 59,
    colors: ["green", "white"],
    size: ["L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "34",
    title: "Big Pony Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1417656_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1417656_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "Finished with our iconic Big Pony, this Polo shirt features bold color-blocking in the season's vibrant shades.",
    price: 80,
    colors: ["gray", "white", "navy"],
    size: ["L", "S"],
    sleeve: "Long Sleeve",
    category: "kids",
  },
  {
    id: "35",
    title: "Striped Mesh Long-Sleeve Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455583_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455583_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "Rich-hued stripes and washed cotton mesh ensure this Polo shirt will be in regular rotation through the cooler months.",
    price: 60,
    colors: ["green", "white"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Long Sleeve",
    category: "kids",
  },
  {
    id: "36",
    title: "Striped Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455570_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455570_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "This Polo shirt features five striped patterns and a pennant-inspired '1967' detail at the front.",
    price: 69,
    colors: ["green", "yellow", "red"],
    size: ["L", "M"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "37",
    title: "Color-Blocked Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455569_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1455569_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "In breathable cotton mesh, this Polo shirt features bold color-blocking and three iterations of our signature embroidered Pony.",
    price: 55,
    colors: ["navy", "yellow"],
    size: ["XL", "M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "38",
    title: "Tie-Dye Ombré Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439600_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439600_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "This Polo shirt achieves its vibrant ombré motif through a multilevel dye process and hand detailing.",
    price: 55,
    colors: ["blue", "white", "orange"],
    size: ["L", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "39",
    title: "Sailboat Cotton Mesh Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439618_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439618_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "In our signature mesh fabric, this Polo shirt features a nautical-inspired print of sailboats and palm trees.",
    price: 55,
    colors: ["blue", "red"],
    size: ["XL", "L", "M", "S"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
  {
    id: "40",
    title: "Print Cotton Jersey Polo Shirt",
    src: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439541_lifestyle?$rl_df_pdp_5_7_lif$",
    src2: "https://www.rlmedia.io/is/image/PoloGSI/s7-1439541_alternate1?$rl_df_pdp_5_7$",
    description: "Boys 8-20",
    content:
      "In soft cotton jersey, this Polo shirt features a resort-inspired print of palm trees, tennis rackets, and bicycles.",
    price: 55,
    colors: ["black", "white"],
    size: ["L", "M"],
    sleeve: "Short Sleeve",
    category: "kids",
  },
];
